<?php

class Regions
{
  public static $allRegions = [
  'East Midlands' => [
  'introduction' => "<p>Derbyshire's Peak District consists of moors in the north and a central limestone plateau crossed by rivers such as the Wye, which have cut gorges and caves in the rock and produced potholes. In a sheltered valley of the Wye lies Bakewell with its medieval bridge and famous for its Bakewell Tarts, where Jane Austen stayed while working on Pride and Prejudice. Not far away is Chatsworth House, home to the Dukes of Devonshire. Immediately south of the Peak District's highest area, Edale offers good walking country.</p>
      <p>Leicester is a largely modern city where in 2012 the remains of King Richard III were discovered in the ruins of Greyfriars Church, beneath what is now a council car park, where he had been hastily buried after the Battle of Bosworth. The remains have since been re-interred in Leicester Cathedral.</p>
      <p>The ancient part of the historic city of Lincoln is situated on a hill rising 200 feet above the River Witham. It had been settled by Celts, Romans, Anglo-Saxons and Danes before William the Conqueror founded Lincoln Castle in 1068. By 1092 a Cathedral had also been built, which was devastated by an earthquake in 1185. Rebuilding began a few years later and resulted in the glorious triple-towered Cathedral, the third largest in England, that has endured to this day.</p>
      <p>For many people Nottingham stands for only one thing - the legend of Robin Hood and his Merrie Men in Sherwood Forest. The forest still exists, although it is very different from that in the evil sheriff's time. Southwell Minster can be seen for miles around and is well worth a visit, for the beauty of the foliage carvings in the chapter house if nothing else. Southwell is also where the first Bramley apple tree began life in about 1805 as a pip planted in a pot by a Mr Bramley.</p>",
  'subregions' => ['Derbyshire', 'Leicestershire', 'Lincolnshire', 'Northamptonshire', 'Nottinghamshire'],
      'image' => 'images/eastmidlands/eastmidlands.jpg'
  ],
  'Scotland' => [
  'introduction' => "<p>With over 11,000 km of coastline, hundreds of islands, majestic mountains in the Highlands, delightful canals, rivers and lochs, the sweeping valleys and heather-clad moorlands of the Borders, and a wealth of wildlife, the beauty of Scotland will take your breath away. Enjoy great walks along the shores of Loch Lomond; do some climbing in the Cairngorms, the Grampian mountains, where you will find Ben Nevis, the highest peak in Britain, or the Arrochar Alps; stroll along the pristine rivers and lochs, full of wild salmon and trout.</p>
      <p>Scotland has a rich and colourful history. Stone circles, thought to date back 5,000 years, are scattered across Scotland's islands. The mightiest artillery fortification in Britain, Fort George northeast of Inverness, was built by the English king as the ultimate defence against further Jacobite unrest after the 1746 defeat at Culloden of Bonnie Prince Charlie. And you will find castles, abbeys and cathedrals everywhere.</p>
      <p>Romantic Inveraray Castle on the shore of Loch Fyne in Argyll is one of Scotland's finest stately homes, while Cawdor Castle, near Nairn, is famed for its connection with Shakespeare's Macbeth, although the actual 11th-century events on which the play is based took place well before the castle was built. The Castle of Mey in Caithness belonged to the late Queen Elizabeth the Queen Mother and Glamis Castle near Forfar in Angus was her childhood home. The magnificent ruins of a motte and bailey castle dating from the 12th century, Castle Huntly in Aberdeenshire, sheltered Robert the Bruce in the 14th century. Dunvegan Castle on Skye, built on a rock in an idyllic loch setting, is the oldest continuously inhabited castle in Scotland and has been the ancestral home of Chiefs of the Clan MacLeod for 800 years.</p>
      <p>In 563 AD St Columba and his followers came from Ireland to the Isle of Iona, just off the Isle of Mull, to spread the gospel in Scotland and the north of England, and the island retains a spiritual atmosphere. The restored medieval abbey, in front of which stands the magnificent 10th-century St Martin's Cross, still holds daily services. Visiting the island is a very special experience.</p>
      <p>With more than 4,500 listed buildings, Scotland's capital Edinburgh is world-renowned for its rich architectural heritage. Edinburgh Castle's oldest part, St Margaret's Chapel, dates from the 12th century, but building went on for centuries after that. The castle houses the Honours (i.e. Crown Jewels) of Scotland, the Stone of Destiny, the famous 15th-century gun Mons Meg and the National War Museum of Scotland. Edinburgh's New Town has imposing squares of Georgian houses and among other treasures to be found in this great city are the Palace of Holyroodhouse, the Queen's official residence in Scotland, the National Galleries of Scotland, St Giles Cathedral, the Scott Monument and Craigmillar Castle, one of the most perfectly preserved castles in the country. The Edinburgh Fringe is the largest art festival in the world and is just one of several festivals taking place in August each year.</p>
      <p>The birthday of Scotland's national poet Robert Burns (1759-96) , of Auld Lang Syne fame, is celebrated each year on 25 January with Burns Night and references to him can be found everywhere, while Sir Walter Scott (1771-1832), whose Ivanhoe is perhaps the best-known of his many novels, is particularly connected with the Borders, where he spent much of his leisure time exploring because of his great interest in the old Border tales and ballads.</p>
      <p>And then there are the distilleries, many of which can be visited, the galleries and museums, the abbeys, the bagpipes, the seals and dolphins ...</p>",
  'subregions' => ['Scottish Borders', 'Dumfries & Galloway', 'Edinburgh', 'Fife', 'Glasgow', 'Scottish Highlands', 'Western Isles, Mull & Skye']
  ]
  ];

}

?>
