<?php

class Regions
{
    public static $allRegions = [
        'London and Middlesex' => [
            'introduction' => "<p>London has a long tradition of vegetarianism, stretching back more than a century to the establishment of the London Vegetarian Society (later VSUK) and it also saw the founding of the Vegan Society in November 1944. But not until 1961, when the first Cranks restaurant was opened in London's trendy Carnaby Street, could vegetarians start to really feel at home. Many other restaurants followed over the next decades.</p>
<p>Nowadays it is a sign of neglect in even the very best hotels and restaurants if they don't have vegetarian, and quite often also one or more vegan, options on their menu. You can find pretty much anything you might fancy, from organic veggie burgers, a wide variety of delicious salads and traditional British fare to an all-you-can-eat Chinese buffet and a gourmet fine dining extravaganza.</p>
<p>See the sights of London, such as Trafalgar Square, Tower Bridge and the Tower of London, Buckingham Palace, St James's Park, the London Eye, St Paul's Cathedral, Big Ben and the Houses of Parliament. Visit the London Dungeon, Madame Tussauds, the National Gallery, the Science Museum and many other great museums housing unique treasures. London's acclaimed theatres offer everything from Shakespeare to musicals, drama and comedy, opera and ballet. Whatever you are interested in, you can find it in London!</p>",
            'subregions' => ['Central London', 'East London', 'North London', 'South London', 'West London', 'Middlesex'],
            'image' => 'images/london/london.png'
        ],
        'East Midlands' => [
            'introduction' => "<p>Derbyshire's Peak District consists of moors in the north and a central limestone plateau crossed by rivers such as the Wye, which have cut gorges and caves in the rock and produced potholes. In a sheltered valley of the Wye lies Bakewell with its medieval bridge and famous for its Bakewell Tarts, where Jane Austen stayed while working on Pride and Prejudice. Not far away is Chatsworth House, home to the Dukes of Devonshire. Immediately south of the Peak District's highest area, Edale offers good walking country.</p>
      <p>Leicester is a largely modern city where in 2012 the remains of King Richard III were discovered in the ruins of Greyfriars Church, beneath what is now a council car park, where he had been hastily buried after the Battle of Bosworth. The remains have since been re-interred in Leicester Cathedral.</p>
      <p>The ancient part of the historic city of Lincoln is situated on a hill rising 200 feet above the River Witham. It had been settled by Celts, Romans, Anglo-Saxons and Danes before William the Conqueror founded Lincoln Castle in 1068. By 1092 a Cathedral had also been built, which was devastated by an earthquake in 1185. Rebuilding began a few years later and resulted in the glorious triple-towered Cathedral, the third largest in England, that has endured to this day.</p>
      <p>For many people Nottingham stands for only one thing - the legend of Robin Hood and his Merrie Men in Sherwood Forest. The forest still exists, although it is very different from that in the evil sheriff's time. Southwell Minster can be seen for miles around and is well worth a visit, for the beauty of the foliage carvings in the chapter house if nothing else. Southwell is also where the first Bramley apple tree began life in about 1805 as a pip planted in a pot by a Mr Bramley.</p>",
            'subregions' => ['Derbyshire', 'Leicestershire', 'Lincolnshire', 'Northamptonshire', 'Nottinghamshire'],
            'image' => 'images/eastmidlands/eastmidlands.jpg'
        ],
        'Scotland' => [
            'introduction' => "<p>With over 11,000 km of coastline, hundreds of islands, majestic mountains in the Highlands, delightful canals, rivers and lochs, the sweeping valleys and heather-clad moorlands of the Borders, and a wealth of wildlife, the beauty of Scotland will take your breath away. Enjoy great walks along the shores of Loch Lomond; do some climbing in the Cairngorms, the Grampian mountains, where you will find Ben Nevis, the highest peak in Britain, or the Arrochar Alps; stroll along the pristine rivers and lochs, full of wild salmon and trout.</p>
      <p>Scotland has a rich and colourful history. Stone circles, thought to date back 5,000 years, are scattered across Scotland's islands. The mightiest artillery fortification in Britain, Fort George northeast of Inverness, was built by the English king as the ultimate defence against further Jacobite unrest after the 1746 defeat at Culloden of Bonnie Prince Charlie. And you will find castles, abbeys and cathedrals everywhere.</p>
      <p>Romantic Inveraray Castle on the shore of Loch Fyne in Argyll is one of Scotland's finest stately homes, while Cawdor Castle, near Nairn, is famed for its connection with Shakespeare's Macbeth, although the actual 11th-century events on which the play is based took place well before the castle was built. The Castle of Mey in Caithness belonged to the late Queen Elizabeth the Queen Mother and Glamis Castle near Forfar in Angus was her childhood home. The magnificent ruins of a motte and bailey castle dating from the 12th century, Castle Huntly in Aberdeenshire, sheltered Robert the Bruce in the 14th century. Dunvegan Castle on Skye, built on a rock in an idyllic loch setting, is the oldest continuously inhabited castle in Scotland and has been the ancestral home of Chiefs of the Clan MacLeod for 800 years.</p>
      <p>In 563 AD St Columba and his followers came from Ireland to the Isle of Iona, just off the Isle of Mull, to spread the gospel in Scotland and the north of England, and the island retains a spiritual atmosphere. The restored medieval abbey, in front of which stands the magnificent 10th-century St Martin's Cross, still holds daily services. Visiting the island is a very special experience.</p>
      <p>With more than 4,500 listed buildings, Scotland's capital Edinburgh is world-renowned for its rich architectural heritage. Edinburgh Castle's oldest part, St Margaret's Chapel, dates from the 12th century, but building went on for centuries after that. The castle houses the Honours (i.e. Crown Jewels) of Scotland, the Stone of Destiny, the famous 15th-century gun Mons Meg and the National War Museum of Scotland. Edinburgh's New Town has imposing squares of Georgian houses and among other treasures to be found in this great city are the Palace of Holyroodhouse, the Queen's official residence in Scotland, the National Galleries of Scotland, St Giles Cathedral, the Scott Monument and Craigmillar Castle, one of the most perfectly preserved castles in the country. The Edinburgh Fringe is the largest art festival in the world and is just one of several festivals taking place in August each year.</p>
      <p>The birthday of Scotland's national poet Robert Burns (1759-96) , of Auld Lang Syne fame, is celebrated each year on 25 January with Burns Night and references to him can be found everywhere, while Sir Walter Scott (1771-1832), whose Ivanhoe is perhaps the best-known of his many novels, is particularly connected with the Borders, where he spent much of his leisure time exploring because of his great interest in the old Border tales and ballads.</p>
      <p>And then there are the distilleries, many of which can be visited, the galleries and museums, the abbeys, the bagpipes, the seals and dolphins ...</p>",
            'subregions' => ['Aberdeenshire and Moray', 'Scottish Borders', 'Dumfries & Galloway', 'Edinburgh', 'Glasgow and Central Scotland', 'Scottish Highlands', 'Western Isles, Mull & Skye'],
            'image' => 'images/scotland/scotland.png'
        ],
        'Wales' => [
            'introduction' => "<p>Modern Wales is famed for its beautiful scenery, world-renowned male voice choirs, history of coal mining and the resilience of its native language – Welsh is still widely spoken and many (if not all) road and other signs are in both Welsh and English.</p>
      <p>But Wales has a complex history - one of conquest and resistance, from the arrival of the Celts and their Druid priests in the Iron Age, the Roman invasion in AD47, the slow Norman penetration of the 11th and 12th centuries and the Edwardian quelling of Welsh independence, to the Welsh rebellions, the best known (and last) of which was that of Owain Glyndwr (immortalized by Shakespeare as Owen Glendower) against England in the early 15th century. After centuries of conflict, Wales was finally united with England in 1536.</p>
      <p>The evidence of this history can be seen all around; in the Roman walls at Caerwent, the great 8th century boundary line of Offa’s Dyke and the many impressive castles – including Caernarfon (see picture), Beaumaris and the ruined Norman castle in Aberystwyth, captured by Owain Glyndwr during his rebellion.</p>
      <p>In addition to the historical attractions, there is much to explore in the landscape of Wales. The Wales Coast Path, the many lakes, rivers and waterfalls, the Gower peninsula and the mountains – such as Gwynedd’s Mount Snowdon, the highest mountain in Wales (a stiff 5km trek to the peak from nearby Llanberis, but very worthwhile for the more adventurous visitor!) and the Brecon Beacons.</p>
      <p>Wales has more to offer than just history and nature however; there are plenty of noteworthy cities and towns to visit. Cardiff, the capital of Wales, has industry as well as history, Hay-on-Wye in Powys is a famous book town with an annual literary festival, Caerphilly in Mid-Glamorgan is famous for its cheese and castle and Llandudno in Conwy is a popular seaside resort.</p>
      <p>Wales, land of mountains and castles, Celts, bards and Druidic lore - there is so much to discover, explore and enjoy!</p>",
            'subregions' => ['North Wales', 'Powys', 'South Wales', 'West Wales'],
            'image' => 'images/wales/wales.jpg'
        ],
        'South West England' => [
            'introduction' => "<p>The West Country is steeped in history with stories of smuggling, piracy, intrigue and magic.</p>
      <p>Stonehenge in Wiltshire is one of the most important megalithic monuments in Europe. Its origins are shrouded in mystery, but it is believed to have had religious and astronomical purposes. Modern-day Druids still celebrate the summer solstice there. Avebury, not far away, has a huge Neolithic stone circle, surrounded by a bank that also encloses the village.</p>
      <p>According to legend Joseph of Arimathea came to Glastonbury in Somerset, buried the Holy Grail on the slopes of its Tor and built a wattle and daub church on the site where the ruins of the Abbey can now be found. According to a later legend King Arthur and his queen were re-buried in this large abbey.</p>
      <p>Dorset boasts the world-famous Jurassic Coast, the city of Bath with its Roman hot springs is well worth a visit, as is the amazing Eden Project in Cornwall.  There are fantastic beaches, picturesque villages and many other things to enjoy in the West Country. And don't forget to try scrumpy (a rough dry cider), Cornish pasties and cream teas!</p>",
            'subregions' => ['Cornwall', 'Devon', 'Dorset (West)', 'Somerset, Bath and Bristol', 'Wiltshire'],
            'image' => 'images/southwest/southwest.jpg'
        ],
        'North West England' => [
            'introduction' => "<p>Chester was an important military city for the Romans, which they called Deva. The medieval city walls follow the line of the Roman wall and incorporate parts of it. In Anglo-Saxon times the city had its own mint and in the 13th century the port became prominent. The nave of the cathedral, on the site of a Norman abbey, was begun in the 14th century but not finished until the 16th. Good examples of both medieval and Victorian black-and-white buildings can also be found. The county is relatively rural, but in the north east Altrincham, where the UK Vegetarian Society is based, and Hale are suburbs of Manchester.</p>
<p>Cumbria is almost synonymous with the Lake District, but Carlisle also should not be missed - it is steeped in Roman and Reiver history and a section of Hadrian's Wall runs just to the north of the town. The Lake District itself is a walker's paradise and is breathtaking, with mountains, fells and lakes such as Coniston Water, Windermere, Ullswater and Rydal Water (see photo). There are a wealth of literary associations. Wordsworth, Coleridge, Ruskin and Southey are lived in the Lake District and many other poets and writers stayed there at various times. For most of his life Donald Watson, who coined the word 'vegan' and founded the UK Vegan Society, also lived there.</p>
<p>The Isle of Man, in the Irish Sea, is not part of the United Kingdom but is an autonomous possession of the British Crown. It has its own Celtic language, Manx, which is now nearly extinct, and its own parliament, the Court of Tynwald, which is one of the oldest legislative assemblies in the world. It is famous for the annual TT motorcycle races and its Manx cats, but also has a fascinating history. Until 1266 is was a dependency of Norway, after which it came under Scottish rule. Neolithic, Bronze Age, Norse and medieval remains abound. Well worth a visit!</p>
<p>Blackpool is undoubtedly the best-known of Lancashire's seaside resorts and was already popular in the 18th century. Cromwell inflicted a decisive defeat on the Royalist forces at the Battle of Preston in 1648 and Richard Arkwright, the inventor of the spinning frame, was born in Preston. Lancaster Castle is associated with John of Gaunt, Duke of Lancaster and son of King Edward III, although he only made brief visits. In later times George Fox, the founder of the Quakers, was twice imprisoned here. Many other fine medieval and Tudor buildings can also be found in the town.</p>
<p>The industrial and commercial centre of Manchester is mainly known for its football teams Manchester United and Manchester City, but it also has a largely 15th-century cathedral, a number of galleries, museums and libraries, and is home to the Hallé orchestra.</p>
Liverpool is the second largest seaport in Britain, with miles of docks along its waterfront. It has a huge Anglican cathedral, begun in 1904 and completed in 1978, and a modernist Roman Catholic cathedral that was opened in 1968. But apart from its football team, what Liverpool is best known for is its music scene. Who has not heard of the Beatles?</p>",
            'subregions' => ['Cheshire', 'Cumbria', 'Isle of Man', 'Lancashire, Greater Manchester, Merseyside'],
            'image' => 'images/northwest/northwest.jpg'
        ],
        'South and South East England' => [
            'introduction' => "<p>Have a meal in Brighton, 'the vegetarian capital' of England, full of vegetarian and vegetarian-friendly cafés and restaurants.</p>
<p>See the White Cliffs of Dover and visit Dover Castle, Dymchurch with its four mile-long Roman sea wall, and many other castles and fortifications along the coast. Enjoy looking round the mediaeval port of Rye, Canterbury Cathedral, Knole and Sissinghurst with their association with Vita Sackville-West, Portsmouth's Naval Dockyards and Battle Abbey, near where the Battle of Hastings was fought.</p>
<p>Laze on the beaches and have a look at the attractions on the Victorian piers. Pop over to the Isle of Wight and visit Carisbrooke Castle, were King Charles I was imprisoned before his execution.</p>
<p>The glorious rolling landscapes of the Downs and the Weald are an invitation to any walker, while stately homes, ancient abbeys and churches, and signs of Iron Age and Roman occupation can be found everywhere.</p>",
            'subregions' => ['Dorset (East)', 'Hampshire', 'Isle of Wight', 'Kent', 'Surrey', 'Sussex'],
            'image' => 'images/southeast/southeast.jpg'
        ],
        'East Anglia' => [
            'introduction' => '<p>Cambridge is one of the most beautiful towns in Britain, if not in Europe. There was a Celtic settlement here before the Roman Conquest on what is known as Castle Hill. At the foot of the hill was a ford across the River Cam and the successive Roman developments probably included the building of a bridge at that point - the only one to have given its name to an English county. The 13th century saw the founding of the first college, after groups of scholars migrated from Oxford. Student hostels in the care of one the masters were established and these were the origins of the college system that still exists today. The Fitzwilliam Museum houses a magnificent collection of works of art of all kinds and the Botanical Gardens in Bateman Street date from 1846. Much punting is done on the river in summer, while the Gog Magog (or Grogingog) \'Hills\' just outside the town, on the crest of which stands the Iron Age fort of Wandlebury, are popular with walkers.</p>
<p>Essex is the most Romanised part of Britain, as the conquerors made Colchester their capital, with many ancient roads still at least in part in use today. It was sacked by Queen Boadicea, described by Tacitus in his Annals, and has a complete 2nd-century wall and the biggest Norman keep in Europe. To see the best of Essex travel through the villages around Halstead, Dunmow and Thaxted, the area where Gustav Holst composed The Planets and H.G. Wells wrote Mr Britling Sees It Through.</p>
<p>Along the banks of the Suffolk border river John Constable painted his great series of Stour pictures and many of the churches, lanes, meadows, mills and farms he depicted can still be seen today. Thomas Gainsborough\'s birthplace can be found at Sudbury, further along the same river. A visit to the beautiful small town of Lavenham, with its great church and superb timber-framed Guildhall is also well worthwhile.</p>
<p>Moving north to Norfolk, a visit to Norwich, with its Norman Castle and Cathedral and many other remarkable features, is a must. But to most people Norfolk means the Broads, vast expanses of water that resulted from centuries of peat working, now explored by many on boating holidays. Also don\'t forget King\'s Lynn, while good beaches can be found along the coast.</p>',
            'subregions' => ['Cambridgeshire', 'Essex', 'Norfolk', 'Suffolk'],
            'image' => 'images/eastanglia/eastanglia.jpg'
        ],
        'North East England' => [
            'introduction' => "<p>From Roman times onwards Northumberland was England's frontier county, with the raiding, pillaging and murder that for centuries had ravaged the county as far south as the Tyne valley only ending with the Act of Union between England and Scotland in 1707, although even after that for some time raiding was not unknown. Powerful families lived in castles, lesser folk in peel towers. It is hill country, with the Cheviots perhaps best known, and there are many rivers running in narrow dales. Between Gilsland and Housesteads is one of the best remaining stretches of Hadrian's Wall and Roman remains can be found everywhere. There are good beaches along the lovely coast.</p>
<p>Tyne & Wear is a metropolitan county, a wedge carved out of Northumberland and Durham. The port of Newcastle-upon-Tyne on the north bank of the Tyne is the administrative centre and boasts a number of bridges across the river. Antony Gormley's huge sculpture called The Angel of the North (see photo) near Gateshead stands close to the motorway and can be seen for miles around.</p>
<p>Yorkshire is the largest county in England and has everything a visitor can wish for - beaches, moors, dales, castles, ruined abbeys and priories, Wensleydale cheese, pretty market towns, moorland villages, country houses and literary connections. Haworth, where the Brontë sisters lived, is outranked only by Stratford-upon-Avon as a literary shrine.</p>
<p>The walled city of York was the military capital of Roman Britain, which they called Eboracum. It was burned down by the Danes in 867 AD and they renamed it Jorvic, from which the current name derives. Nothing is left of Anglo-Saxon and Danish York, but the Normans found a thriving little trading centre there. They too burnt it, in 1069, and then rebuilt the walls. It is still possible to walk along top of the walls, an experience not to be missed. Medieval York is everywhere, with The Shambles and Stonegate some of the best preserved examples. But the dominant feature of York is its magnificent Minster, built between 1220 and 1470 and  at least the fourth successive church on this site.</p>",
            'subregions' => ['Northumberland', 'Tyne & Wear', 'Yorkshire'],
            'image' => 'images/northeast/northeast.jpg'
        ],
        'Thames and Chilterns' => [
            'introduction' => "<p>Oxford, city of the 'dreaming spires', has the second oldest university in Europe (after the Sorbonne in Paris) with organised teaching that can be traced back to the 12th century. The city's history and architecture are amazing. The Ashmolean Museum houses a vast collection of antiquities from numerous countries as well as many Old Master paintings and drawings. The Bodleian Library is one of the oldest in the world, housing many rare manuscripts.</p>
<p>Reading has always been an important centre, as it is strategically situated on the Thames. Jane Austen went to school there and, more notoriously, Oscar Wilde was imprisoned in Reading Gaol. Windsor Castle, one of the Queen's residences, is the largest inhabited castle in the world and many parts of it are open to the public. Windsor Great Park, a huge area of wooded park with some magnificent gardens, is in effect a vast nature reserve where all kinds of animals can be found. Also in Windsor is Legoland, so you don't have to go to Denmark for a fun-filled day for all the family.</p>
<p>The countryside in Bedfordshire and Hertfordshire is quiet and gentle. Ampthill is a well-preserved little town of historical interest, with many picturesque cottages and gracious Georgian houses, while Dunstable is a modern town that still retains a few ancient and Victorian buildings. The ancient city of St Albans is a fascinating place to visit, with a wealth of features dating from Roman times to the present day. It was one of the largest and most important Roman towns ever founded in England.</p>",
            'subregions' => ['Bedfordshire', 'Berkshire', 'Hertfordshire', 'Oxfordshire'],
            'image' => 'images/thamesandchilterns/thamesandchilterns.jpg'
        ],
        'Heart of England' => [
            'introduction' => "<p>Apart from the West Midlands, the Heart of England has a rural character. The Forest of Dean in Gloucestershire has miles of woodland paths and and abounds in wildlife, while further west are the low hills of the Cotswolds with its picturesque villages and typical stone houses. The city of Gloucester has a magnificent cathedral, and in the spa town of Cheltenham a wealth of Regency houses border elegant squares, crescents and terraces.</p>
<p>Orchards, meadows and hops can be found in Herefordshire. Ross-on-Wye is a modest market town set on a red sandstone cliff above a lovely sweep of the River Wye and the city of Hereford too is edged by the Wye. Its cathedral was founded by King Offa of Mercia, builder of the famous Offa's Dyke, although much of it was added on or restored in later times.</p>
<p>Malvern in Worcestershire, on the eastern slopes of the Malvern Hills, is known for its mineral springs and the ancient cathedral city of Worcester is certainly worth a visit. Walkers will enjoy the hills around Church Stretton in Shropshire, of which Long Mynd is perhaps best known, and fine walks can also he had among the hills of the Caradoc range. Shrewbury is one of the best preserved medieval towns in the country. The church of St Mary's was built around 1200, has a fine stone spire, a 14th-century carved nave roof and lovely stained glass.</p>
<p>Warwickshire is Shakespeare country. Stratford-upon-Avon was his birthplace and he lived there for a considerable part of his life. Once he had achieved fame in London he was able to buy New Place, regarded as the finest house in Stratford. His tomb can be found in Holy Trinity Church and there are many buildings in Stratford with a direct association with Shakespeare, not least his wife's home Anne Hathaway's Cottage. The town of Warwick has a magnificent castle and some medieval houses, although a fire that broke out in the centre of the town in 1694 destroyed more than 250 buildings.</p>
<p>West Midlands is a small 'new' county created out of parts of Worcestershire, Staffordshire and Warwickshire. Apart from Coventry, which was devastatingly bombed in World War II and is famous for its modern cathedral, it mainly consists of Britain's second largest city Birmingham. This is an industrial city, but it also has a thriving cultural life, more miles of canals than Venice, the famous Balti triangle where every variety of Indian curry can be found, and the Bull Ring shopping centre. The headquarters of the UK Vegan Society are also in Birmingham.</p>",
            'subregions' => ['Gloucestershire', 'Herefordshire', 'Shropshire', 'Warwickshire', 'West Midlands', 'Worcestershire'],
            'image' => 'images/heartofengland/heartofengland.jpg'
        ]
    ];
}

?>
