<?php
class Codes
{
    public static $allCodes = ['H' => 'Hotel',
    'G' => 'Guest house',
    'PH' => 'Private house (B&B)',
    'INS' => 'Inspected under one of the schemes operating in Britain; full details can be obtained from the establishment concerned if required',
    'L' => 'Licensed',
    'DA' => 'Disabled access',
    'V' => 'Exclusively vegetarian: entries without this code also cater for non-vegetarians',
    'Ve' => 'Also catering for vegans; please mention you are a vegan when you contact the establishment',
    'Vegan' => 'Exclusively vegan',
    'NS' => 'No smoking anywhere on the premises (may include garden)pNS Smoking restricted to certain areas only',
    'CN' => 'Car necessary: a car/taxi journey or extended walk is needed from the nearest public transport',
    'Acc2' => 'Accommodation for two adults; children travelling with their parents can sometimes be accommodated additionally',
    'CatA' => 'over £40.00',
    'CatB' => '£27.50-£40.00',
    'CatC' => 'under £27.50',
    'R' => 'Restaurant',
    'C' => 'Café',
    'P' => 'Pub',
    'R/P' => 'Restaurant/Pub',
    'R/C' => 'Restaurant/Café',
    'a' => 'A selection of vegetarian dishes daily, as well as non-vegetarian food; quite often at least one vegan dish is also on the menu',
    'b' => 'Vegetarian food only',
    'c' => 'Vegetarian and vegan food only',
    'd' => 'Vegan food only',
    'w' => 'Wholefood',
    'org' => 'Organic produce used whenever possible',
    'F' => 'Fairtrade products used'];
}
